name: Documentation

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docs/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Initialize DocFX
      run: dotnet tool update -g docfx

    - name: DocFX Build
      run: docfx docs/docfx.json
      continue-on-error: false

    - name: Publish DocFX Site
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ github.token }}
        branch: gh-pages
        folder: docs/_site
