# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: .NET

on:
  push:
    branches: [main]
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet.yml
  pull_request:
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet.yml
  workflow_dispatch:

env:
  dotnet_version: 8.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_version}}

      - name: Install dependencies
        run: dotnet restore

      - name: Build FlashyDJ.Slotmaps
        run: dotnet build src/Slotmaps/Slotmaps.csproj -c ${{matrix.configuration}} --no-restore

  run-tests:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.dotnet_version}}

      - name: XUnit Test for Slotmaps.Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: ./tests/Slotmaps.Tests
          msbuild_configuration: Release
          report_name: Slotmaps.Tests
          report_title: Slotmaps Test
          gist_name: slotmaps_tests.md
          gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{secrets.GIST_TOKEN}}
          set_check_status_from_test_outcome: true
